version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: seraaj
      POSTGRES_PASSWORD: seraaj
      POSTGRES_DB: seraaj
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "seraaj"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://seraaj:seraaj@db:5432/seraaj
      - SECRET_KEY=changeme
      - APP_ENV=local
      - RESET_ON_START=true
      - SEED_DEMO_DATA=true
      - BACKEND_PORT=${BACKEND_PORT:-8000}
    volumes:
      - ./backend:/code
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
volumes:
  db_data:
