name: ci
on: [push, pull_request]
jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: seraaj
          POSTGRES_USER: seraaj
          POSTGRES_PASSWORD: seraaj
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          pip install -r backend/requirements.txt
      - name: Tests
        env:
          DATABASE_URL: postgresql+psycopg2://seraaj:seraaj@localhost:5432/seraaj
        run: |
          cd backend && pytest -q
